alias ls='ls --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -l --color=auto'
alias lla='ls -Al --color=auto'

alias vi='nvim $1'
alias vim='nvim $1'
alias view='nvim -R'
alias vimdiff='nvim -d'
alias svim='sudoedit $1'
